import {ALL_PLAYERS} from './data/players.js';
function encyclopediaCards(){
  return ALL_PLAYERS.map(p=>{
    const owned=save.collection.includes(p.id);
    const c=cardModel(p,developmentFor(save,p.id));
    const abilities=c.abilities.slice(0,3).map(a=>'<span class="ability-chip '+(a.kind==='special'?'ability-special':'')+'">'+a.name+' '+a.ratePercent+'%</span>').join('');
    const image=p.image||'';
    return '<div class="player-card compact-player encyclopedia-player '+(owned?'owned':'locked')+(p.limited?' limited-card':'')+'" data-player-id="'+p.id+'">'+
      '<div class="player-portrait"><span class="rank-badge">'+c.rank+'</span>'+(p.limited?'<span class="limited-badge">LIMITED</span>':'')'+(!owned?'<span class="lock-badge">未獲得</span>':'')+(image?'<img src="'+image+'" alt="'+p.name+'" loading="lazy">':'<div class="portrait-fallback"><span>'+p.name.split(' ').map(x=>x[0]).join('').slice(0,3)+'</span></div>')+'</div>'+
      '<div class="player-head"><strong>'+c.name+'</strong><b>'+c.overall+'</b></div>'+
      '<span class="player-meta">'+c.pos+' · '+c.era+'</span>'+
      '<div class="mini-stats"><span>打 '+c.stats.contact+'</span><span>パ '+c.stats.power+'</span><span>守 '+c.stats.field+'</span><span>走 '+c.stats.speed+'</span></div>'+
      '<div class="ability-list">'+abilities+'</div>'+
      (owned?'<button type="button" class="action release-player" data-id="'+p.id+'">放出</button>':'')+
    '</div>';
  }).join('');
}
function renderCollection(){card.innerHTML='<h2>選手名鑑</h2><p>登録 '+save.collection.length+' / '+ALL_PLAYERS.length+' 名　タップで3D選手表示</p><div class="player-grid">'+(encyclopediaCards()||'<p>選手データがありません</p>')+'</div><button class="action back" id="back">ホームへ戻る</button>';$('back').onclick=()=>setMode('home');bindPlayerCards();}
function renderGacha(){card.innerHTML='<h2>スカウト</h2><p>無料・コイン無制限</p><div id="reveal" class="reveal">—</div><div class="row"><button class="action" id="pull">スカウトする</button><button class="action" id="back">戻る</button></div>';$('pull').onclick=()=>{const r=pullOnce(save,ALL_PLAYERS);if(r.error){$('reveal').textContent='コイン不足';return}save=r.state;persist();void playGachaReveal({rarity:r.result.rarity,name:r.result.player.name});
void getCloudSave().then(cloud=>{if(cloud){save={...save,currency:cloud.currency,collection:cloud.collection,team:cloud.team,progress:cloud.progress,settings:cloud.settings,matches:cloud.matches,wins:cloud.wins};persist();}}).catch(()=>{});$('reveal').textContent=r.result.rarity+'　'+r.result.player.name+(r.duplicate?'　重複→'+r.duplicateReward+'コイン':'');};$('back').onclick=()=>setMode('home');}
function updateMatchHUD(){$('matchhud').textContent=`${match.inning}回${match.half==='TOP'?'表':'裏'}　${match.score.away} - ${match.score.home}`;$('inning-label').textContent=`${match.inning}回${match.half==='TOP'?'表':'裏'}`;$('away-score').textContent=match.score.away;$('home-score').textContent=match.score.home;$('count-label').textContent=`B ${match.balls} / S ${match.strikes} / O ${match.outs}`;}
function pitch(){if(pitchState!=='idle'||match.ended)return;pitchState='pitch';t=0;const pitcherPlayer=ALL_PLAYERS[0];const pitch=choosePitch({count:[match.balls,match.strikes],profile:aiProfile(pitcherPlayer,developmentFor(save,pitcherPlayer.id))});window.__lastPitch=pitch;$('pitch-readout').textContent=pitch;void playMatchEvent('pitch',pitch);}
function swing(){if(pitchState!=='pitch')return;pitchState='hit';t=0;const batterPlayer=ALL_PLAYERS[4];const decision=chooseSwing({pitch:window.__lastPitch||'FASTBALL',profile:aiProfile(batterPlayer,developmentFor(save,batterPlayer.id))});const outcome=decision.action==='TAKE'?resolvePitch({timing:.25,contact:.1}):resolvePitch({timing:decision.timing,contact:decision.contact});match=applyOutcome(match,outcome);updateMatchHUD();$('pitch-readout').textContent=outcome;if(['SINGLE','DOUBLE','TRIPLE','HOME_RUN'].includes(outcome)){fielderTarget={x:(Math.random()-.5)*18,z:Math.random()*16+2};fieldingFrom={x:0,z:0};}const type=outcome==='HOME_RUN'?'home_run':outcome==='DOUBLE'?'double':outcome==='TRIPLE'?'triple':outcome==='SINGLE'?'single':outcome==='OUT'?'out':outcome==='STRIKE'?'strikeout':outcome==='BALL'?'walk':'play';void playMatchEvent(type,outcome);}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{setMode(b.dataset.mode);if(b.dataset.mode==='match'){match=createMatchState();updateMatchHUD();}}));
$('pitch').addEventListener('click',pitch);$('swing').addEventListener('click',swing);$('matchback').addEventListener('click',()=>setMode('home'));persist();updateProfileUI();
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);
function animate(){requestAnimationFrame(animate);animatePlayer(pitcher,pitchState==='pitch'?'pitch':'idle',pitchState==='pitch'?t:0);animatePlayer(batter,pitchState==='hit'?'swing':'idle',pitchState==='hit'?t:0);if(pitchState==='hit'&&fielderTarget){const lead=fielders[0];const dx=fielderTarget.x-lead.position.x,dz=fielderTarget.z-lead.position.z;const d=Math.hypot(dx,dz);const step=Math.min(.12,d);if(d>.1){lead.position.x+=dx/d*step;lead.position.z+=dz/d*step;animatePlayer(lead,'run',t*2)}}if(pitchState==='pitch'){t+=.018;const p=Math.min(t,1);ball.position.set(0,2.1-.25*p,3-11*p);if(p>=1){const missedSwing=Math.random()<.55; if(missedSwing){const outcome=Math.random()<.62?'STRIKE':'BALL';match=applyOutcome(match,outcome);updateMatchHUD();$('pitch-readout').textContent=outcome;void playMatchEvent(outcome==='STRIKE'?'strikeout':'walk',outcome);} pitchState='idle';ball.position.set(0,2.1,3)}}else if(pitchState==='hit'){t+=.018;const p=Math.min(t,1);ball.position.set(4*p,2.1+7*p-5*p*p,-8-18*p);if(p>=1){pitchState='idle';ball.position.set(0,2.1,3)}}renderer.render(scene,camera)}animate();
void getCloudSave().then(cloud=>{if(cloud){save={...save,currency:cloud.currency,collection:cloud.collection,team:cloud.team,progress:cloud.progress,settings:cloud.settings,matches:cloud.matches,wins:cloud.wins};saveGame(save);currency.textContent=save.unlimitedCoins?'∞':save.currency.toLocaleString("ja-JP");}}).catch(()=>{});
window.__gameReady=true;window.__gameVersion="baseball-3d-web-20260920-02";